name: seqcal
version: 0.1.0.0
synopsis: Sequent calculus proof generator
description: See report.pdf
maintainer: Jonas van der Schaaf <jonas.vanderschaaf@student.uva.nl>, Emiel Wiedijk <emiel.wiedijk@student.uva.nl>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck

library:
  source-dirs: lib

tests:
  simpletests:
    main: Main.lhs
    source-dirs: test
    dependencies:
      - seqcal
      - QuickCheck
      - hspec
